### ISSUE TITLE
Pull requests don't pass 

### ISSUE THREAD

**Issue by yarax** [chentsulin/awesome-graphql#157]
Guys, seems like new awesome bot doesn't pass new pull requests, because already existing links in README:
https://github.com/chentsulin/awesome-graphql/pull/156
https://travis-ci.org/chentsulin/awesome-graphql/builds/190590030
So as you see tests are failed because of 
```
Issues :-(
> Links 
  1. [L124] 404 https://github.com/rmosolgo/graphql-relay-ruby  
  2. [L293] 301 https://github.com/kriasoft/graphql-starter-kit  → https://github.com/kriasoft/nodejs-api-starter 
```
not because of swagger2graphql itself

**Comment by pluma** [comment]
I've addressed the most recent batch of errors in #164

I guess #162 is a more permanent solution to this problem but would require running awesome bot manually every now and then to catch outdated URLs.

**Comment by yarax** [comment]
Can I help here with something?

**Comment by pluma** [comment]
FWIW the contributor badge just means I've had a PR merged. I'm not a maintainer.

That said, it's probably past the maintainer's bedtime right now: https://time.is/Taipei

So I guess just wait a day or so ;)

**Comment by pluma** [comment]
@yarax FYI #164 was merged and master is now green again (until the next URI falls out of date).

**Comment by yarax** [comment]
Tried again. Still fails because of other links :( https://github.com/chentsulin/awesome-graphql/pull/167

**Comment by m1guelpf** [comment]
I think you should really consider #162

**Comment by yarax** [comment]
@m1guelpf can you please explain what should I consider? 
162 PR is about checking only changes. 
I'm suggesting my changes and getting back error in another part of file:
```
Issues :-(
> Links 
  1. [L365]  http://swapi.graphene-python.org Connection reset by peer 
```

**Comment by pluma** [comment]
Awesome!

@stubailo Any chance of getting green PRs merged now?

**Comment by yarax** [comment]
Thank you @stubailo !
